[[language]]
name = "typst"
indent = { tab-width = 4, unit = " "}
auto-format = true
formatter = { command = "typstyle", args = [ "--indent-width", "4", "--wrap-text" ] }
language-servers = [ "tinymist" ]

[language-server.tinymist]
command = "tinymist"

